package diag

import (
	"os"
	"reflect"
	"testing"
)

func TestParseResolvConf(t *testing.T) {
	// Create a temporary resolv.conf for testing
	content := `
# Generated by NetworkManager
search localdomain
nameserver 8.8.8.8
nameserver 1.1.1.1
`
	tmpfile, err := os.CreateTemp("", "resolv.conf")
	if err != nil {
		t.Fatalf("Failed to create temp file: %v", err)
	}
	defer os.Remove(tmpfile.Name())

	if _, err := tmpfile.Write([]byte(content)); err != nil {
		t.Fatalf("Failed to write to temp file: %v", err)
	}
	tmpfile.Close()

	// Run parseResolvConf
	nameservers, err := parseResolvConf(tmpfile.Name())
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	expected := []string{"8.8.8.8", "1.1.1.1"}
	if !reflect.DeepEqual(nameservers, expected) {
		t.Errorf("Expected %v, got %v", expected, nameservers)
	}
}

func TestTestNameserver(t *testing.T) {
	// Let's test against a known good public resolver.
	// Since network conditions can vary, a reliable test might abstract this,
	// but for now an integration-style test against 8.8.8.8 is a good start.

	result := testNameserver("8.8.8.8", "redhat.com")
	
	if !result.Passed {
		t.Errorf("Expected resolution to pass via 8.8.8.8, but failed. Error: %s", result.ErrorMsg)
	}
	if result.HostTested != "redhat.com" {
		t.Errorf("Expected target host redhat.com, got %s", result.HostTested)
	}
}
